name: barcode
description: >-
  Barcode generation library for Dart that can generate
  generic drawing operations for any backend.
homepage: https://github.com/DavBfr/dart_barcode/tree/master/barcode
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.2.9

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  qr: ^3.0.0

dev_dependencies:
  convert: ^3.0.1
  flutter_lints: ^3.0.1
  test: ^1.19.0
