name: barcode
description: >-
  Barcode generation library for Dart that can generate
  generic drawing operations for any backend.
author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/barcode
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.0-nullsafety

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety
  qr: ^2.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
