name: barcode
description: >-
  Barcode generation library for Dart that can generate
  generic drawing operations for any backend.
author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/barcode
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  qr: ^2.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
