language: dart
dist: bionic
dart:
  - stable
  - dev

addons:
  apt:
    packages:
      - lcov

script:
  - make analyze-barcode
  - make analyze-image
  - make test
  - test -z "$(git status --porcelain)"
