language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
      - poppler-utils
      - imagemagick
      - lcov
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
  - export PATH=$HOME/flutter/bin:$PATH
  - flutter doctor
  - flutter --version

script:
  - make analyze-barcode
  - make analyze-image
  - make test
  - test -z "$(git status --porcelain)"
