name: example
description: BarcodeWidget example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"

dependencies:
  barcode_widget:
  flutter:
    sdk: flutter

dependency_overrides:
  barcode:
    path: ../../barcode
  barcode_widget:
    path: ../

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
