name: barcode_widget
description: >-
  Barcode generation widget for Flutter with support for standard barcodes.
author: David PHAM-VAN <dev.nfet.net@gmail.com
homepage: https://github.com/DavBfr/dart_barcode/tree/master/flutter
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 1.2.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode: ^1.3.0
  meta: ^1.1.5

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
