name: barcode_widget
description: >-
  Barcode generation widget for Flutter with support for standard barcodes.
author: David PHAM-VAN <dev.nfet.net@gmail.com
homepage: https://github.com/DavBfr/dart_barcode/tree/master/flutter
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.0-nullsafety.1

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  barcode: ^2.0.0-nullsafety
  flutter:
    sdk: flutter

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
