name: barcode_widget
description: >-
  Barcode generation widget for Flutter with support for standard barcodes.
homepage: https://github.com/DavBfr/dart_barcode/tree/master/flutter
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  barcode: ^2.2.2
  flutter:
    sdk: flutter

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
