name: example
description: BarcodeWidget example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  barcode_image:
  barcode_widget:
  file_selector:
  flutter:
    sdk: flutter
  google_fonts:
  image: ^4.0.0
  path_provider:
  pdf:

dependency_overrides:
  barcode:
    path: ../barcode
  barcode_image:
    path: ../image
  barcode_widget:
    path: ../flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
