name: example
description: BarcodeWidget example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  barcode_image:
  barcode_widget:
  flutter:
    sdk: flutter
  google_fonts: 2.0.0-nullsafety.0
  open_file:
    git: https://github.com/rsixel/open_file
  path_provider: ">=2.0.0-0"
  pdf: ">=3.0.0-0"

dependency_overrides:
  barcode:
    path: ../barcode
  barcode_image:
    path: ../image
  barcode_widget:
    path: ../flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ">=1.10.0"

flutter:
  uses-material-design: true
