name: example
description: BarcodeWidget example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_image:
  barcode_widget:
  google_fonts:
  open_file:
  path_provider:
  pdf:

dependency_overrides:
  barcode_widget:
    path: ../flutter
  barcode_image:
    path: ../image
  barcode:
    path: ../barcode

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
