name: barcode_image
description: >-
  Barcode generation library for Dart that can generate
  barcodes using the image library.
author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/image
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.0-nullsafety

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"

dependencies:
  args: ^1.5.0
  barcode: ^2.0.0-nullsafety
  image: ^2.1.0
  meta: ^1.1.8

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  crypto:
  pedantic: ^1.10.0-nullsafety
  pubspec_extract: ^1.3.1
  test: ^1.16.0-nullsafety

executables:
  barcode:
