name: barcode_image
description: >-
  Barcode generation library for Dart that can generate
  barcodes using the image library.
_author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/image
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.3.0
  barcode: ^2.2.4
  image: ^4.0.6
  meta: ^1.7.0

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  build_runner: ^2.4.4
  crypto: ^3.0.2
  flutter_lints: ^2.0.1
  pubspec_extract: ^2.0.5
  test: ^1.21.4

executables:
  barcode:

pubspec_extract:
  destination: lib/src/pubspec.dart
