name: barcode_image
description: >-
  Barcode generation library for Dart that can generate
  barcodes using the image library.
author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/image
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  barcode: ^1.16.0
  meta: ^1.1.8
  image: ^2.1.0
  args: ^1.5.0

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  test:
  crypto:
  pedantic: 1.9.2
  pubspec_extract: ^1.3.1

executables:
  barcode:
